### ISSUE TITLE
Hotlink to jquery seems to be broken

### ISSUE THREAD

**Issue by joelasaro** [jamesweakley/TreeSizeHtml#3]
Looks like you were hotlinking to a jquery.js file here:
http://static.jstree.com/v.1.0pre/jquery.js

I don't know much about JavaScript, but it looks like there are better options for getting that file:
http://stackoverflow.com/questions/1383442/is-there-a-version-of-jquery-somewhere-that-i-can-hotlink-to-without-hosting-the

I used this with success for myself:
http://code.jquery.com/jquery-2.0.3.js

**Comment by jamesweakley** [comment]
Thanks Joel, I've committed a fix for this.
